[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
reclaim = "HBLDx6SUJdUxHp2bHKM7Nxi28y3bJpQSxoddE79HeXNZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/hadisaleh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
